common: &default_settings
  server: <%= ENV["POIROT_SERVER"] %>
  source: instedd-hub
  stdout: <%= ENV["POIROT_STDOUT"] %>
  suppress_rails_log: <%= ENV["POIROT_SUPPRESS_RAILS_LOG"] %>
  enabled: <%= !!ENV["POIROT_SERVER"] || !!ENV["POIROT_STDOUT"] %>
  debug: false

development:
  <<: *default_settings
  mute:
   - /assets/
   - /_resque/

production:
  <<: *default_settings

test:
  <<: *default_settings
  enabled: false
